// Generates supabase/seed.sql from src/sample-data.js, so the database and the
// in-browser sample data stay the same.   node scripts/make-seed.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import * as S from '../src/sample-data.js'
import { courseHandicap } from '../src/scoring.js'
import { teeRating } from '../src/games.js'

const q = v => (v == null ? 'null' : typeof v === 'number' || typeof v === 'boolean' ? String(v) : `'${String(v).replace(/'/g, "''")}'`)
const j = v => `${q(JSON.stringify(v))}::jsonb`
const arr = xs => `'{${xs.join(',')}}'::bigint[]`
const rows = (table, cols, data) => data.length ? `insert into public.${table} (${cols.join(', ')}) values\n  ${data.map(r => `(${r.join(', ')})`).join(',\n  ')};\n` : ''

// The login email for the sample admin (id 0) comes from .env, so it isn't committed.
const envFile = new URL('../.env', import.meta.url)
const OWNER_EMAIL = process.env.OWNER_EMAIL ?? (existsSync(envFile) && readFileSync(envFile, 'utf8').match(/^OWNER_EMAIL=(.*)$/m)?.[1].trim().toLowerCase()) ?? null
if (!OWNER_EMAIL) console.warn('OWNER_EMAIL not set in .env: no sample member will be linked to a login.')
const C = S.COURSE
const par = C.holes.map(h => h.par)

// Others' rounds today, made up from their handicaps (same recipe as the in-browser sample).
function fieldScores(m, thru) {
  const r = S.rng(m.id * 53 + 11), ch = courseHandicap(m.hcp, teeRating(C))
  return C.holes.slice(0, thru).map(h => {
    const x = r()
    return h.par + (x < 0.15 - ch * 0.004 ? -1 : x < 0.74 - ch * 0.02 ? 0 : x < 0.95 - ch * 0.008 ? 1 : 2)
  })
}
const mine = S.CURRENT_ROUND
const field = S.FIELD.filter(([id]) => !mine.players.includes(id)).map(([id, thru, tee]) => {
  const m = S.MEMBERS.find(x => x.id === id), gross = thru ? fieldScores(m, thru) : []
  return ['current_date', id, j([{ m: id }]), q('stroke'),
    j(par.map((p, i) => [gross[i] ?? p])), j(par.map((_, i) => i < gross.length)), q(tee ?? null)]
})

const sql = `-- Sample data. GENERATED by scripts/make-seed.mjs from src/sample-data.js; edit those, not this.
-- Wipes all app data and reloads it. Dates are relative to the day it's loaded.

truncate public.club_settings, public.courses, public.tees, public.holes, public.members, public.buddies,
  public.pin_sheets, public.tee_slots, public.bookings, public.booking_players, public.guest_visits,
  public.game_settings, public.game_prefs, public.rounds, public.events restart identity cascade;

insert into public.club_settings (id, guest_allowance) values (1, ${S.GUEST_RULES.allowance});
insert into public.courses (id, name, guest_points) values (1, ${q(C.name)}, ${S.GUEST_RULES.costByCourse[C.name]});
${rows('tees', ['course_id', 'key', 'name', 'colour', 'rating', 'slope', 'sort'], C.tees.map((t, i) => [1, q(t.key), q(t.name), q(t.colour), q(t.rating), q(t.slope), i]))}
${rows('holes', ['course_id', 'n', 'name', 'par', 'si', 'green_depth', 'green_width', 'yards'], C.holes.map(h => [1, h.n, q(h.name), h.par, h.si, h.greenDepth, h.greenWidth, j(h.yards)]))}
${rows('members', ['id', 'name', 'gui', 'hcp_index', 'admin', 'email'], S.MEMBERS.map(m => [m.id, q(m.name), q(m.gui), m.hcp, !!m.admin, q(m.id === S.ME_ID ? OWNER_EMAIL : null)]))}
-- Link the login if it already exists (new logins are linked by the on_auth_user_created trigger).
update public.members m set user_id = u.id from auth.users u where m.email = lower(u.email);

${rows('buddies', ['member_id', 'buddy_id'], S.BUDDIES.map(b => [S.ME_ID, b]))}
${rows('guest_visits', ['member_id', 'date', 'guest_name', 'guest_club', 'course_id', 'points'],
  Object.entries(S.GUEST_HISTORY).flatMap(([id, xs]) => xs.map(x => [id, q(x.date), q(x.guest), q(x.club), 1, x.points])))}
${rows('game_prefs', ['group_size', 'game_key'], Object.entries(S.GAME_SETTINGS.pref).map(([n, k]) => [n, q(k)]))}
insert into public.pin_sheets (course_id, date, set_at, set_by, pins)
  values (1, current_date, (current_date + time ${q(S.PIN_SHEET.setAt)}) at time zone 'Europe/Dublin', null, ${j(S.PIN_SHEET.pins)});

-- My group's card in progress, and others out today.
${rows('rounds', ['date', 'created_by', 'lineup', 'game', 'pairing', 'scores', 'done'],
  [['current_date', S.ME_ID, j(mine.players.map(m => ({ m }))), q(mine.game), mine.pairing, j(mine.scores), j(mine.done)]])}
${rows('rounds', ['date', 'created_by', 'lineup', 'game', 'scores', 'done', 'tee_time'], field)}
${rows('events', ['id', 'name', 'team_a', 'team_b', 'club', 'start_date', 'days', 'style', 'fmt', 'players', 'team', 'matches', 'created_by'],
  S.EVENTS.map(e => [e.id, q(e.name), j(e.A), j(e.B), true, 'current_date', e.days, q('ryder'), q('bbl'), arr(e.players), j(e.team),
    j(Object.fromEntries(Object.entries(e.matches).map(([d, ms]) => [d, ms.map(({ a, b, tee }) => ({ a, b, tee }))]))), S.ME_ID]))}
-- Tee sheet for the next 7 days, with other members already booked on some times.
do $$
declare
  others bigint[] := ${arr(S.MEMBERS.filter(m => m.id !== S.ME_ID && !S.BUDDIES.includes(m.id)).map(m => m.id))};
  d date; s bigint; b bigint; pick bigint[];
begin
  perform setseed(0.42);
  for d in select current_date + i from generate_series(0, 6) i loop
    insert into public.tee_slots (course_id, date, start_time, twilight)
      select 1, d, m, m >= 15 * 60 from generate_series(7 * 60 + 30, 16 * 60 + 30, 10) m
       where not (m >= 12 * 60 + 20 and m < 13 * 60);
    for s in select id from public.tee_slots where date = d order by start_time loop
      select array_agg(x) into pick from (
        select x from unnest(others) x order by random() limit least(4, floor(random() * 5.2)::int)) t;
      for i in 1 .. coalesce(cardinality(pick), 0) loop
        insert into public.bookings (slot_id, booked_by) values (s, pick[i]) returning id into b;
        insert into public.booking_players (booking_id, slot_id, member_id) values (b, s, pick[i]);
      end loop;
    end loop;
  end loop;
end $$;

-- Explicit ids above, so move the id counters past them.
select setval(pg_get_serial_sequence('public.members', 'id'), (select max(id) from public.members));
select setval(pg_get_serial_sequence('public.courses', 'id'), (select max(id) from public.courses));
select setval(pg_get_serial_sequence('public.events', 'id'), (select max(id) from public.events));

select (select count(*) from public.members) as members, (select count(*) from public.holes) as holes,
       (select count(*) from public.tee_slots) as tee_slots, (select count(*) from public.booking_players) as booked_players,
       (select count(*) from public.guest_visits) as guest_visits, (select count(*) from public.rounds) as rounds,
       (select count(*) from public.events) as events,
       (select user_id is not null from public.members where id = ${S.ME_ID}) as owner_login_linked;
`
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql)
console.log('Wrote supabase/seed.sql')
