-- TeeMates schema: tables, Row Level Security, and the functions the app calls.
--
-- Security model
--   * Only signed-in users who are on the members list can see anything (anon sees nothing).
--   * A login is linked to a member by email (see link_member_to_user).
--   * Committee members can edit pins, games and events.
--   * Bookings and guest points can only be written through book_tee_time(), which checks
--     spaces and points in one transaction, so double bookings and negative balances can't happen.

-- ---------------------------------------------------------------- club and course

create table public.club_settings (
  id int primary key default 1 check (id = 1),          -- single row
  guest_allowance int not null default 36 check (guest_allowance >= 0)
);

create table public.courses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  guest_points int not null default 3 check (guest_points >= 0)   -- points a guest costs on this course
);

create table public.tees (
  course_id bigint not null references public.courses on delete cascade,
  key text not null,
  name text not null,
  colour text not null,
  rating numeric(4,1),
  slope int,
  sort int not null default 0,
  primary key (course_id, key)
);

create table public.holes (
  course_id bigint not null references public.courses on delete cascade,
  n int not null check (n between 1 and 18),
  name text not null,
  par int not null check (par between 3 and 6),
  si int not null check (si between 1 and 18),
  green_depth int not null,
  yards jsonb not null,                                   -- { "black": 441, "white": 402, ... }
  primary key (course_id, n),
  unique (course_id, si)
);

-- ---------------------------------------------------------------- members

create table public.members (
  id bigint generated by default as identity primary key,
  name text not null,
  gui text unique,                                        -- Golf Ireland number
  hcp_index numeric(4,1) not null default 54,
  committee boolean not null default false,
  email text unique check (email = lower(email)),         -- used to link a login; never sent to other members
  user_id uuid unique references auth.users on delete set null
);

create table public.buddies (
  member_id bigint not null references public.members on delete cascade,
  buddy_id bigint not null references public.members on delete cascade,
  primary key (member_id, buddy_id),
  check (member_id <> buddy_id)
);

-- The signed-in user's member id (null if they're not on the members list).
create function public.current_member_id() returns bigint
language sql stable security definer set search_path = '' as $$
  select id from public.members where user_id = auth.uid()
$$;

create function public.is_committee() returns boolean
language sql stable security definer set search_path = '' as $$
  select coalesce((select committee from public.members where user_id = auth.uid()), false)
$$;

-- Link a new login to the member with the same email.
create function public.link_member_to_user() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  update public.members set user_id = new.id
   where email = lower(new.email) and user_id is null;
  return new;
end $$;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.link_member_to_user();

-- ---------------------------------------------------------------- pins

create table public.pin_sheets (
  course_id bigint not null references public.courses on delete cascade,
  date date not null,
  set_at timestamptz not null default now(),
  set_by bigint references public.members on delete set null,
  pins jsonb not null,                                    -- [{ "hole": 1, "yardsOn": 8, "side": "L" }, ...]
  primary key (course_id, date)
);

-- ---------------------------------------------------------------- tee times, bookings, guest points

create table public.tee_slots (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses on delete cascade,
  date date not null,
  start_time smallint not null check (start_time between 0 and 1439),   -- minutes after midnight
  capacity smallint not null default 4 check (capacity between 1 and 4),
  twilight boolean not null default false,
  unique (course_id, date, start_time)
);

create table public.bookings (
  id bigint generated by default as identity primary key,
  slot_id bigint not null references public.tee_slots on delete cascade,
  booked_by bigint not null references public.members on delete cascade,
  created_at timestamptz not null default now()
);

create table public.booking_players (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings on delete cascade,
  slot_id bigint not null references public.tee_slots on delete cascade,
  member_id bigint references public.members on delete cascade,      -- null for a guest
  guest_name text,
  guest_club text,
  guest_gui text,
  check ((member_id is null) <> (guest_name is null)),
  unique (slot_id, member_id)                                        -- a member can't be on one tee time twice
);
create index on public.booking_players (booking_id);

-- Guest points ledger: one row per guest brought, charged to the host member.
create table public.guest_visits (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members on delete cascade,
  booking_player_id bigint references public.booking_players on delete set null,
  date date not null,
  guest_name text not null,
  guest_club text,
  course_id bigint not null references public.courses,
  points int not null check (points >= 0)
);
create index on public.guest_visits (member_id, date);

-- Backstop: a member's points used in a year can never exceed the allowance,
-- however a row got there.
create function public.check_guest_balance() returns trigger
language plpgsql set search_path = '' as $$
declare
  used int;
  allowance int := (select guest_allowance from public.club_settings where id = 1);
begin
  select coalesce(sum(points), 0) into used from public.guest_visits
   where member_id = new.member_id and date_trunc('year', date) = date_trunc('year', new.date);
  if used > allowance then
    raise exception 'You don''t have enough guest points for this booking.' using errcode = 'P0001';
  end if;
  return null;
end $$;

create constraint trigger guest_balance_never_negative
  after insert or update on public.guest_visits
  for each row execute function public.check_guest_balance();

-- ---------------------------------------------------------------- games, rounds, events

create table public.game_settings (
  game_key text primary key,
  enabled boolean not null default true,
  allowance_pct int check (allowance_pct between 0 and 100)
);

create table public.game_prefs (
  group_size int primary key check (group_size between 2 and 4),
  game_key text not null
);

create table public.rounds (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  created_by bigint not null default public.current_member_id() references public.members on delete cascade,
  players bigint[] not null,                    -- member ids in card order; players[1] is the creator
  game text,
  pairing int not null default 0 check (pairing between 0 and 2),
  scores jsonb not null default '[]',           -- gross per hole per player: [[4,5,4,4], ...]
  done jsonb not null default '[]',             -- [true, true, false, ...]
  submitted jsonb not null default '{}',
  tee_time text,                                -- shown on the leaderboard before they start
  updated_at timestamptz not null default now()
);
create index on public.rounds (date);

create table public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  team_a jsonb not null,                        -- { "name": "Blues", "col": "#19335A" }
  team_b jsonb not null,
  active boolean not null default false,
  days int not null default 1 check (days between 1 and 3),
  course text not null,
  format text not null,
  players bigint[] not null default '{}',
  team jsonb not null default '{}',             -- { "<member id>": "A" | "B" }
  matches jsonb not null default '{}'           -- { "1": [{ a, b, tee, res }], ... }
);
create unique index one_active_event on public.events (active) where active;

-- ---------------------------------------------------------------- Row Level Security

alter table public.club_settings   enable row level security;
alter table public.courses         enable row level security;
alter table public.tees            enable row level security;
alter table public.holes           enable row level security;
alter table public.members         enable row level security;
alter table public.buddies         enable row level security;
alter table public.pin_sheets      enable row level security;
alter table public.tee_slots       enable row level security;
alter table public.bookings        enable row level security;
alter table public.booking_players enable row level security;
alter table public.guest_visits    enable row level security;
alter table public.game_settings   enable row level security;
alter table public.game_prefs      enable row level security;
alter table public.rounds          enable row level security;
alter table public.events          enable row level security;

-- Nothing for anonymous visitors.
revoke all on all tables in schema public from anon;

-- Members can read reference data.
create policy "members read" on public.club_settings for select to authenticated using (public.current_member_id() is not null);
create policy "members read" on public.courses       for select to authenticated using (public.current_member_id() is not null);
create policy "members read" on public.tees          for select to authenticated using (public.current_member_id() is not null);
create policy "members read" on public.holes         for select to authenticated using (public.current_member_id() is not null);
create policy "members read" on public.tee_slots     for select to authenticated using (public.current_member_id() is not null);
create policy "members read" on public.game_settings for select to authenticated using (public.current_member_id() is not null);
create policy "members read" on public.game_prefs    for select to authenticated using (public.current_member_id() is not null);
create policy "members read" on public.pin_sheets    for select to authenticated using (public.current_member_id() is not null);
create policy "members read" on public.events        for select to authenticated using (public.current_member_id() is not null);
create policy "members read" on public.rounds        for select to authenticated using (public.current_member_id() is not null);

-- The member list, without emails or login ids.
create policy "members read" on public.members for select to authenticated using (public.current_member_id() is not null);
revoke all on public.members from authenticated;
grant select (id, name, gui, hcp_index, committee) on public.members to authenticated;

-- Your own buddies.
create policy "own buddies" on public.buddies for select to authenticated using (member_id = public.current_member_id());
create policy "add own buddies" on public.buddies for insert to authenticated with check (member_id = public.current_member_id());
create policy "remove own buddies" on public.buddies for delete to authenticated using (member_id = public.current_member_id());

-- Your own bookings (ones you made or are playing in). Writes only via book_tee_time().
-- The helper runs without RLS so the two policies don't refer to each other in a loop.
create function public.my_booking_ids() returns setof bigint
language sql stable security definer set search_path = '' as $$
  select id from public.bookings where booked_by = public.current_member_id()
  union
  select booking_id from public.booking_players where member_id = public.current_member_id()
$$;
create policy "own bookings" on public.bookings for select to authenticated
  using (id in (select public.my_booking_ids()));
create policy "own booking players" on public.booking_players for select to authenticated
  using (booking_id in (select public.my_booking_ids()));
revoke insert, update, delete on public.bookings, public.booking_players, public.guest_visits, public.tee_slots from authenticated;

-- Guest points: your own; the committee sees everyone's.
create policy "own or committee" on public.guest_visits for select to authenticated
  using (member_id = public.current_member_id() or public.is_committee());

-- Committee edits pins, games and events.
create policy "committee writes" on public.pin_sheets    for all to authenticated using (public.is_committee()) with check (public.is_committee());
create policy "committee writes" on public.game_settings for all to authenticated using (public.is_committee()) with check (public.is_committee());
create policy "committee writes" on public.game_prefs    for all to authenticated using (public.is_committee()) with check (public.is_committee());
create policy "committee writes" on public.events        for all to authenticated using (public.is_committee()) with check (public.is_committee());

-- Rounds: you can start and update your own cards.
create policy "own rounds insert" on public.rounds for insert to authenticated with check (created_by = public.current_member_id());
create policy "own rounds update" on public.rounds for update to authenticated
  using (created_by = public.current_member_id()) with check (created_by = public.current_member_id());

-- ---------------------------------------------------------------- functions the app calls

-- Tee sheet for a day, with who's booked on each time.
-- Times for the next 14 days are created the first time someone looks at that day.
create function public.get_tee_sheet(p_date date) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_course bigint := (select id from public.courses order by id limit 1);
begin
  if public.current_member_id() is null then
    raise exception 'Only members can see the tee sheet.' using errcode = '42501';
  end if;
  if p_date between current_date and current_date + 13 then
    insert into public.tee_slots (course_id, date, start_time, twilight)
    select v_course, p_date, m, m >= 15 * 60
      from generate_series(7 * 60 + 30, 16 * 60 + 30, 10) m
     where not (m >= 12 * 60 + 20 and m < 13 * 60)          -- held for the Ladies' Comp
    on conflict do nothing;
  end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'id', s.id, 'date', s.date, 'time', s.start_time, 'capacity', s.capacity, 'twilight', s.twilight,
             'players', coalesce((
               select jsonb_agg(jsonb_build_object('name', coalesce(m.name, bp.guest_name), 'memberId', bp.member_id, 'guest', bp.member_id is null) order by bp.id)
                 from public.booking_players bp left join public.members m on m.id = bp.member_id
                where bp.slot_id = s.id), '[]'::jsonb))
           order by s.start_time)
      from public.tee_slots s
     where s.course_id = v_course and s.date = p_date), '[]'::jsonb);
end $$;

-- Book a tee time for me, plus other members and guests, in one transaction.
-- The tee time row is locked, so two people booking the last spaces at once are handled
-- one after the other; the second sees the spaces gone. My member row is locked while
-- guest points are checked, so two bookings at once can't both spend the same points.
create function public.book_tee_time(p_slot_id bigint, p_member_ids bigint[] default '{}', p_guests jsonb default '[]')
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_me bigint := public.current_member_id();
  v_slot public.tee_slots;
  v_ids bigint[];
  v_guests int := jsonb_array_length(coalesce(p_guests, '[]'));
  v_taken int;
  v_cost int := 0;
  v_used int;
  v_booking bigint;
  g jsonb;
  v_bp bigint;
begin
  if v_me is null then
    raise exception 'Only members can book tee times.' using errcode = '42501';
  end if;

  select * into v_slot from public.tee_slots where id = p_slot_id for update;
  if not found then
    raise exception 'That tee time no longer exists.' using errcode = 'P0001';
  end if;
  if v_slot.date < current_date then
    raise exception 'That tee time has passed.' using errcode = 'P0001';
  end if;

  v_ids := array[v_me] || coalesce(p_member_ids, '{}');
  if (select count(distinct x) from unnest(v_ids) x) <> cardinality(v_ids) then
    raise exception 'A player is listed twice.' using errcode = 'P0001';
  end if;
  if (select count(*) from public.members where id = any(v_ids)) <> cardinality(v_ids) then
    raise exception 'One of those players isn''t a member.' using errcode = 'P0001';
  end if;
  if exists (select 1 from public.booking_players where slot_id = v_slot.id and member_id = any(v_ids)) then
    raise exception 'One of your group is already booked on this time.' using errcode = 'P0001';
  end if;

  for g in select * from jsonb_array_elements(coalesce(p_guests, '[]')) loop
    if coalesce(trim(g->>'name'), '') = '' then
      raise exception 'Every guest needs a name.' using errcode = 'P0001';
    end if;
    if coalesce(g->>'gui', '') <> '' and (g->>'gui') !~ '^\d{6,10}$' then
      raise exception 'GUI numbers are 6–10 digits.' using errcode = 'P0001';
    end if;
  end loop;

  select count(*) into v_taken from public.booking_players where slot_id = v_slot.id;
  if cardinality(v_ids) + v_guests > v_slot.capacity - v_taken then
    raise exception 'Sorry, those spaces have just been taken. Pick another time.' using errcode = 'P0001';
  end if;

  if v_guests > 0 then
    perform 1 from public.members where id = v_me for update;
    v_cost := (select guest_points from public.courses where id = v_slot.course_id);
    select coalesce(sum(points), 0) into v_used from public.guest_visits
     where member_id = v_me and date_trunc('year', date) = date_trunc('year', v_slot.date::timestamp);
    if v_used + v_cost * v_guests > (select guest_allowance from public.club_settings where id = 1) then
      raise exception 'You don''t have enough guest points for this booking.' using errcode = 'P0001';
    end if;
  end if;

  insert into public.bookings (slot_id, booked_by) values (v_slot.id, v_me) returning id into v_booking;
  insert into public.booking_players (booking_id, slot_id, member_id)
    select v_booking, v_slot.id, x from unnest(v_ids) with ordinality u(x, o) order by o;
  for g in select * from jsonb_array_elements(coalesce(p_guests, '[]')) loop
    insert into public.booking_players (booking_id, slot_id, guest_name, guest_club, guest_gui)
      values (v_booking, v_slot.id, trim(g->>'name'), nullif(trim(g->>'club'), ''), nullif(g->>'gui', ''))
      returning id into v_bp;
    insert into public.guest_visits (member_id, booking_player_id, date, guest_name, guest_club, course_id, points)
      values (v_me, v_bp, v_slot.date, trim(g->>'name'), nullif(trim(g->>'club'), ''), v_slot.course_id, v_cost);
  end loop;

  return jsonb_build_object(
    'id', v_booking, 'date', v_slot.date, 'time', v_slot.start_time,
    'guests', v_guests, 'pointsUsed', v_cost * v_guests,
    'players', (select jsonb_agg(coalesce(m.name, bp.guest_name || ' (guest)') order by bp.id)
                  from public.booking_players bp left join public.members m on m.id = bp.member_id
                 where bp.booking_id = v_booking));
end $$;

-- My upcoming bookings, with everyone in each booking.
create function public.get_my_bookings() returns jsonb
language sql stable security definer set search_path = '' as $$
  select coalesce(jsonb_agg(jsonb_build_object(
           'id', b.id, 'date', s.date, 'time', s.start_time,
           'players', (select jsonb_agg(coalesce(m.name, bp.guest_name || ' (guest)') order by bp.id)
                         from public.booking_players bp left join public.members m on m.id = bp.member_id
                        where bp.booking_id = b.id))
         order by s.date, s.start_time), '[]'::jsonb)
    from public.bookings b join public.tee_slots s on s.id = b.slot_id
   where s.date >= current_date
     and (b.booked_by = public.current_member_id()
          or exists (select 1 from public.booking_players bp where bp.booking_id = b.id and bp.member_id = public.current_member_id()))
$$;

-- Make one event the active one (only one can be).
create function public.set_active_event(p_event_id bigint, p_active boolean) returns void
language plpgsql security invoker set search_path = '' as $$
begin
  if p_active then
    update public.events set active = false where active and id <> p_event_id;
  end if;
  update public.events set active = p_active where id = p_event_id;
end $$;

-- Only signed-in users can call the functions; each one checks membership itself.
revoke execute on all functions in schema public from public, anon;
grant execute on function public.current_member_id(), public.is_committee(), public.my_booking_ids(), public.get_tee_sheet(date),
  public.book_tee_time(bigint, bigint[], jsonb), public.get_my_bookings(), public.set_active_event(bigint, boolean)
  to authenticated;
