-- 1. One admin role: committee folds into admin. Admins grant access and run club-wide events,
--    pins and games.
-- 2. Access requests: someone whose email isn't approved can leave their name; admins see it
--    under "Access requests" in Members & access and approve or decline. No emails are sent.

-- ---------------------------------------------------------------- committee → admin

update public.members set admin = true where committee;

drop policy "committee writes" on public.pin_sheets;
drop policy "committee writes" on public.game_settings;
drop policy "committee writes" on public.game_prefs;
drop policy "committee writes" on public.events;
drop policy "own or committee" on public.guest_visits;

create policy "admin writes" on public.pin_sheets    for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin writes" on public.game_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin writes" on public.game_prefs    for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin writes" on public.events        for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "own or admin" on public.guest_visits for select to authenticated
  using (member_id = public.current_member_id() or public.is_admin());

drop function public.admin_save_member(bigint, text, text, text, numeric, boolean, boolean);
drop function public.is_committee();
alter table public.members drop column committee;

create or replace function public.admin_list_members() returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can manage access.' using errcode = '42501';
  end if;
  return coalesce((select jsonb_agg(jsonb_build_object(
      'id', id, 'name', name, 'gui', gui, 'hcp', hcp_index, 'email', email,
      'admin', admin, 'signedIn', user_id is not null) order by name)
    from public.members), '[]'::jsonb);
end $$;

-- ---------------------------------------------------------------- access requests

create table public.access_requests (
  id bigint generated by default as identity primary key,
  email text not null unique check (email = lower(email)),
  name text not null check (length(name) between 1 and 80),
  created_at timestamptz not null default now()
);
alter table public.access_requests enable row level security;
revoke all on public.access_requests from anon, authenticated;
grant select on public.access_requests to authenticated;
create policy "admins read" on public.access_requests for select to authenticated using (public.is_admin());

-- Leave a request. Callable before signing in, so it validates everything itself.
create function public.request_access(p_email text, p_name text) returns void
language plpgsql security definer set search_path = '' as $$
declare v_email text := lower(trim(p_email)); v_name text := trim(p_name);
begin
  if v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' or length(v_email) > 200 then
    raise exception 'Enter your email address.' using errcode = 'P0001';
  end if;
  if coalesce(v_name, '') = '' or length(v_name) > 80 then
    raise exception 'Enter your name.' using errcode = 'P0001';
  end if;
  if exists (select 1 from public.members where email = v_email) then
    raise exception 'That email is already approved. Create your account instead.' using errcode = 'P0001';
  end if;
  if (select count(*) from public.access_requests) >= 100 and not exists (select 1 from public.access_requests where email = v_email) then
    raise exception 'Too many requests are waiting. Please contact the club.' using errcode = 'P0001';
  end if;
  insert into public.access_requests (email, name) values (v_email, v_name)
    on conflict (email) do update set name = excluded.name, created_at = now();
end $$;

create function public.admin_decline_request(p_id bigint) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can manage access.' using errcode = '42501';
  end if;
  delete from public.access_requests where id = p_id;
end $$;

-- Add (p_id null) or update a member. Setting an email approves it (and clears any request
-- from that email); clearing it removes access.
create function public.admin_save_member(
  p_id bigint, p_name text, p_email text, p_gui text default null, p_hcp numeric default 54, p_admin boolean default false
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_me bigint := public.current_member_id();
  v_email text := nullif(lower(trim(p_email)), '');
  v_old public.members;
  v_id bigint := p_id;
begin
  if not public.is_admin() then
    raise exception 'Only admins can manage access.' using errcode = '42501';
  end if;
  if coalesce(trim(p_name), '') = '' then
    raise exception 'Enter a name.' using errcode = 'P0001';
  end if;
  if v_email is not null and v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'That doesn''t look like an email address.' using errcode = 'P0001';
  end if;
  if nullif(trim(p_gui), '') is not null and trim(p_gui) !~ '^\d{6,10}$' then
    raise exception 'GUI numbers are 6–10 digits.' using errcode = 'P0001';
  end if;
  if p_hcp is null or p_hcp < -10 or p_hcp > 54 then
    raise exception 'Handicap index must be between +10 and 54.' using errcode = 'P0001';
  end if;
  if v_email is not null and exists (select 1 from public.members where email = v_email and id is distinct from p_id) then
    raise exception 'Another member already has that email.' using errcode = 'P0001';
  end if;
  if p_id = v_me and (not p_admin or v_email is null) then
    raise exception 'You can''t remove your own admin rights or access. Ask another admin.' using errcode = 'P0001';
  end if;

  if p_id is null then
    insert into public.members (name, email, gui, hcp_index, admin)
      values (trim(p_name), v_email, nullif(trim(p_gui), ''), p_hcp, p_admin)
      returning id into v_id;
  else
    select * into v_old from public.members where id = p_id for update;
    if not found then
      raise exception 'That member no longer exists.' using errcode = 'P0001';
    end if;
    update public.members
       set name = trim(p_name), email = v_email, gui = nullif(trim(p_gui), ''), hcp_index = p_hcp, admin = p_admin,
           user_id = case when v_email is distinct from v_old.email then null else user_id end
     where id = p_id;
    if v_old.user_id is not null and v_email is distinct from v_old.email then
      delete from auth.users where id = v_old.user_id;
    end if;
  end if;

  if v_email is not null then
    delete from public.access_requests where email = v_email;
  end if;
  update public.members m set user_id = u.id from auth.users u
   where m.id = v_id and m.user_id is null and v_email is not null and lower(u.email) = v_email;
  return v_id;
end $$;

revoke execute on function public.request_access(text, text), public.admin_decline_request(bigint),
  public.admin_save_member(bigint, text, text, text, numeric, boolean) from public;
grant execute on function public.request_access(text, text) to anon, authenticated;
grant execute on function public.admin_decline_request(bigint), public.admin_save_member(bigint, text, text, text, numeric, boolean) to authenticated;
