-- Player events: a member on one tee time challenges another group on the same day.
-- Someone in the other group accepts or declines. Only the players on those two tee times
-- (and admins) can see it.
--
-- style  'fourball' = four-ball v four-ball (team A is the inviting group)
--        'ryder'    = mixed teams, two from each four-ball on each team
-- format fourball: 'best2' (best 2 Stableford per hole), 'all4' (all 4 Stableford), 'bestball' (match play, best net)
--        ryder:    'bbl' (better ball off the low), 'bbstab' (better ball Stableford), 'bbscr' (better ball scratch)
-- players: snapshot when proposed: [{ id: booking player id, name, memberId, guest, group: 'A'|'B', team: 'A'|'B' }]

create table public.player_events (
  id bigint generated by default as identity primary key,
  date date not null,
  slot_a bigint not null references public.tee_slots on delete cascade,
  slot_b bigint not null references public.tee_slots on delete cascade,
  created_by bigint not null references public.members on delete cascade,
  style text not null check (style in ('fourball', 'ryder')),
  format text not null,
  team_names jsonb not null,                    -- { "A": "...", "B": "..." }
  players jsonb not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'cancelled')),
  responded_by bigint references public.members on delete set null,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  check (slot_a <> slot_b),
  check ((style = 'fourball' and format in ('best2', 'all4', 'bestball')) or (style = 'ryder' and format in ('bbl', 'bbstab', 'bbscr')))
);
create index on public.player_events (slot_a);
create index on public.player_events (slot_b);

alter table public.player_events enable row level security;
revoke all on public.player_events from anon, authenticated;
grant select on public.player_events to authenticated;
create policy "players on either tee time, or admins" on public.player_events for select to authenticated
  using (public.is_admin() or exists (select 1 from public.booking_players bp
          where bp.slot_id in (slot_a, slot_b) and bp.member_id = public.current_member_id()));

-- Everyone on a tee time, in booking order.
create function public.slot_players(p_slot bigint) returns table (id bigint, name text, member_id bigint, guest boolean)
language sql stable security definer set search_path = '' as $$
  select bp.id, coalesce(m.name, bp.guest_name), bp.member_id, bp.member_id is null
    from public.booking_players bp left join public.members m on m.id = bp.member_id
   where bp.slot_id = p_slot order by bp.id
$$;
revoke execute on function public.slot_players(bigint) from public, anon, authenticated;

-- Propose an event. p_teams: { "<booking player id>": "A" | "B" } (Ryder Cup only).
create function public.create_player_event(
  p_slot_a bigint, p_slot_b bigint, p_style text, p_format text, p_team_names jsonb, p_teams jsonb default '{}'
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_me bigint := public.current_member_id();
  a public.tee_slots; b public.tee_slots;
  v_players jsonb; v_id bigint; v_na int; v_nb int;
begin
  select * into a from public.tee_slots where id = p_slot_a;
  select * into b from public.tee_slots where id = p_slot_b;
  if a.id is null or b.id is null or a.id = b.id then
    raise exception 'Pick another group''s tee time.' using errcode = 'P0001';
  end if;
  if not exists (select 1 from public.booking_players where slot_id = a.id and member_id = v_me) then
    raise exception 'You can only start an event from your own tee time.' using errcode = '42501';
  end if;
  if a.date <> b.date then
    raise exception 'Both tee times must be on the same day.' using errcode = 'P0001';
  end if;
  if a.date < current_date then
    raise exception 'That day has passed.' using errcode = 'P0001';
  end if;
  if not exists (select 1 from public.booking_players where slot_id = b.id and member_id is not null) then
    raise exception 'There''s no member in that group to accept.' using errcode = 'P0001';
  end if;
  if exists (select 1 from public.player_events where status in ('pending', 'accepted')
              and (slot_a in (a.id, b.id) or slot_b in (a.id, b.id))) then
    raise exception 'One of those groups is already in an event.' using errcode = 'P0001';
  end if;
  if coalesce(trim(p_team_names->>'A'), '') = '' or coalesce(trim(p_team_names->>'B'), '') = '' then
    raise exception 'Give both teams a name.' using errcode = 'P0001';
  end if;

  select count(*) into v_na from public.slot_players(a.id);
  select count(*) into v_nb from public.slot_players(b.id);
  if p_style = 'ryder' then
    if v_na <> 4 or v_nb <> 4 then
      raise exception 'Ryder Cup needs two full four-balls.' using errcode = 'P0001';
    end if;
    -- every player on a team, and two from each four-ball on each team
    if (select count(*) from (select id from public.slot_players(a.id) union all select id from public.slot_players(b.id)) p
         where p_teams->>(p.id::text) in ('A', 'B')) <> 8
       or (select count(*) from public.slot_players(a.id) p where p_teams->>(p.id::text) = 'A') <> 2
       or (select count(*) from public.slot_players(b.id) p where p_teams->>(p.id::text) = 'A') <> 2 then
      raise exception 'Each team needs two players from each four-ball.' using errcode = 'P0001';
    end if;
  elsif p_style = 'fourball' then
    if v_na < 2 or v_nb < 2 then
      raise exception 'Each group needs at least two players.' using errcode = 'P0001';
    end if;
  else
    raise exception 'Pick a team style.' using errcode = 'P0001';
  end if;

  select jsonb_agg(jsonb_build_object('id', p.id, 'name', p.name, 'memberId', p.member_id, 'guest', p.guest, 'group', p.grp,
           'team', case when p_style = 'ryder' then p_teams->>(p.id::text) else p.grp end) order by p.grp, p.id)
    into v_players
    from (select *, 'A' as grp from public.slot_players(a.id) union all select *, 'B' from public.slot_players(b.id)) p;

  insert into public.player_events (date, slot_a, slot_b, created_by, style, format, team_names, players)
    values (a.date, a.id, b.id, v_me, p_style, p_format,
            jsonb_build_object('A', trim(p_team_names->>'A'), 'B', trim(p_team_names->>'B')), v_players)
    returning id into v_id;
  return v_id;
end $$;

-- Accept or decline. Anyone (member) in the invited group.
create function public.respond_player_event(p_id bigint, p_accept boolean) returns void
language plpgsql security definer set search_path = '' as $$
declare e public.player_events; v_now jsonb;
begin
  select * into e from public.player_events where id = p_id for update;
  if not found then
    raise exception 'That event no longer exists.' using errcode = 'P0001';
  end if;
  if not exists (select 1 from public.booking_players where slot_id = e.slot_b and member_id = public.current_member_id()) then
    raise exception 'Only the invited group can answer.' using errcode = '42501';
  end if;
  if e.status <> 'pending' then
    raise exception 'That invitation has already been answered or cancelled.' using errcode = 'P0001';
  end if;
  if p_accept then
    -- The groups must be the same as when the teams were proposed.
    select jsonb_agg(id order by id) into v_now from (select id from public.slot_players(e.slot_a) union all select id from public.slot_players(e.slot_b)) p;
    if v_now <> (select jsonb_agg((x->>'id')::bigint order by (x->>'id')::bigint) from jsonb_array_elements(e.players) x) then
      raise exception 'The groups have changed since this was proposed. Ask for a new invitation.' using errcode = 'P0001';
    end if;
  end if;
  update public.player_events
     set status = case when p_accept then 'accepted' else 'declined' end,
         responded_by = public.current_member_id(), responded_at = now()
   where id = p_id;
end $$;

-- Cancel: the person who proposed it, or an admin.
create function public.cancel_player_event(p_id bigint) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not exists (select 1 from public.player_events where id = p_id and (created_by = public.current_member_id() or public.is_admin())) then
    raise exception 'Only the person who proposed it can cancel it.' using errcode = '42501';
  end if;
  update public.player_events set status = 'cancelled' where id = p_id and status in ('pending', 'accepted');
end $$;

revoke execute on function public.create_player_event(bigint, bigint, text, text, jsonb, jsonb),
  public.respond_player_event(bigint, boolean), public.cancel_player_event(bigint) from public, anon;
grant execute on function public.create_player_event(bigint, bigint, text, text, jsonb, jsonb),
  public.respond_player_event(bigint, boolean), public.cancel_player_event(bigint) to authenticated;
