-- The club office cancels or moves a member's booking (admins only), with an optional note. Every member on the
-- booking gets a notice (it drops down in their app until they OK it). Moving keeps the same players, guests and
-- booker; the usual checks apply at the new time (room, the 2-hour gap) except when tee times open, as for any
-- admin booking. Scored cards stop a move or a cancel: a round under way stays as it is.

create table public.booking_notices (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members on delete cascade,
  kind text not null check (kind in ('cancelled', 'moved')),
  date date not null,                       -- the day of the booking (its new day, when moved)
  old_time smallint not null,
  new_time smallint,                        -- moved: the new time
  new_date date,                            -- moved: the new day (same as date)
  note text,
  created_at timestamptz not null default now(),
  seen boolean not null default false
);
create index on public.booking_notices (member_id) where not seen;
alter table public.booking_notices enable row level security;
create policy "Members see their own notices" on public.booking_notices for select to authenticated using (member_id = public.current_member_id());
grant select on public.booking_notices to authenticated;

-- get_tee_sheet: each player says which booking they're on (the office cancels or moves a whole booking).
create or replace function public.get_tee_sheet(p_date date)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_course bigint := (select id from public.courses order by id limit 1);
begin
  if public.current_member_id() is null then
    raise exception 'Only members can see the tee sheet.' using errcode = '42501';
  end if;
  if p_date between current_date and current_date + 366 then
    insert into public.tee_slots (course_id, date, start_time, twilight)
    select v_course, p_date, m, m >= 15 * 60
      from generate_series(7 * 60 + 30, 16 * 60 + 30, 10) m
     where not (m >= 12 * 60 + 20 and m < 13 * 60)
    on conflict do nothing;
  end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'id', s.id, 'date', s.date, 'time', s.start_time, 'capacity', s.capacity, 'twilight', s.twilight,
             'players', coalesce((
               select jsonb_agg(jsonb_build_object(
                        'id', bp.id, 'name', coalesce(m.name, bp.guest_name), 'memberId', bp.member_id, 'bookingId', bp.booking_id,
                        'bookedBy', b.booked_by,
                        'guest', bp.member_id is null, 'hcp', case when bp.member_id is null then bp.guest_hcp else m.hcp_index end)
                      order by bp.id)
                 from public.booking_players bp left join public.members m on m.id = bp.member_id join public.bookings b on b.id = bp.booking_id
                where bp.slot_id = s.id), '[]'::jsonb))
           order by s.start_time)
      from public.tee_slots s
     where s.course_id = v_course and s.date = p_date), '[]'::jsonb);
end $function$;

-- Shared by cancel and move: lock the booking, check it can change, and take it off its tee time (unscored cards,
-- any on-the-day match it was part of, guest points back, the booking). → the booking as it was
create function public.office_take_off(p_booking bigint, p_why text) returns public.bookings
language plpgsql security definer set search_path = '' as $$
declare b public.bookings; v_lineups jsonb; v_bps bigint[]; v_date date;
begin
  if not public.is_admin() then
    raise exception 'Only the club office can change members'' bookings.' using errcode = '42501';
  end if;
  select * into b from public.bookings where id = p_booking for update;
  if not found then raise exception 'That booking no longer exists.' using errcode = 'P0001'; end if;
  select date into v_date from public.tee_slots where id = b.slot_id;
  if v_date < current_date then raise exception 'That tee time has passed.' using errcode = 'P0001'; end if;
  select jsonb_agg(jsonb_build_object('m', member_id)) filter (where member_id is not null), array_agg(id) into v_lineups, v_bps
    from public.booking_players where booking_id = b.id;
  if exists (select 1 from public.rounds r where r.slot_id = b.slot_id and exists (select 1 from jsonb_array_elements(coalesce(v_lineups, '[]')) x where r.lineup @> jsonb_build_array(x))
               and exists (select 1 from jsonb_array_elements(r.done) d where d = 'true')) then
    raise exception 'This group has already started scoring, so the booking can''t change.' using errcode = 'P0001';
  end if;
  delete from public.rounds r where r.slot_id = b.slot_id and exists (select 1 from jsonb_array_elements(coalesce(v_lineups, '[]')) x where r.lineup @> jsonb_build_array(x));
  update public.player_events e set status = 'cancelled', cancel_note = p_why, cancelled_at = now(), cancelled_by = public.current_member_id()
   where e.status in ('pending', 'accepted') and e.date >= current_date
     and exists (select 1 from jsonb_array_elements(e.players) p where (p->>'id')::bigint = any(v_bps));
  delete from public.guest_visits where booking_player_id = any(v_bps);
  delete from public.bookings where id = b.id;
  return b;
end $$;
revoke execute on function public.office_take_off(bigint, text) from public, anon, authenticated;

create function public.admin_cancel_booking(p_booking bigint, p_note text default null) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare b public.bookings; v_slot public.tee_slots; v_ids bigint[];
begin
  select array_agg(member_id) filter (where member_id is not null) into v_ids from public.booking_players where booking_id = p_booking;
  b := public.office_take_off(p_booking, 'The club office cancelled the booking');
  select * into v_slot from public.tee_slots where id = b.slot_id;
  insert into public.booking_notices (member_id, kind, date, old_time, note)
    select x, 'cancelled', v_slot.date, v_slot.start_time, nullif(trim(left(p_note, 300)), '') from unnest(v_ids) x;
  return jsonb_build_object('told', cardinality(coalesce(v_ids, '{}')));
end $$;

create function public.admin_move_booking(p_booking bigint, p_slot bigint, p_note text default null) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare b public.bookings; v_old public.tee_slots; v_new public.tee_slots; v_ids bigint[]; v_guests jsonb; r jsonb;
begin
  select array_agg(member_id order by id) filter (where member_id is not null),
         coalesce(jsonb_agg(jsonb_build_object('name', guest_name, 'club', guest_club, 'gui', guest_gui, 'hcp', guest_hcp) order by id) filter (where member_id is null), '[]')
    into v_ids, v_guests from public.booking_players where booking_id = p_booking;
  select s.* into v_old from public.tee_slots s join public.bookings bk on bk.slot_id = s.id where bk.id = p_booking;
  select * into v_new from public.tee_slots where id = p_slot;
  if v_new.id is null or v_new.id = v_old.id then raise exception 'Pick a different tee time.' using errcode = 'P0001'; end if;
  b := public.office_take_off(p_booking, 'The club office moved the ' || public.hhmm(v_old.id) || ' tee time');
  -- Same booker, players and guests at the new time (refusals there undo everything).
  r := public.book_as(b.booked_by, p_slot, array(select x from unnest(v_ids) x where x <> b.booked_by), v_guests, false);
  insert into public.booking_notices (member_id, kind, date, old_time, new_time, new_date, note)
    select x, 'moved', v_new.date, v_old.start_time, v_new.start_time, v_new.date, nullif(trim(left(p_note, 300)), '') from unnest(v_ids) x;
  return r;
end $$;

-- OK on a notice: seen (mine only).
create function public.seen_booking_notice(p_id bigint) returns void
language sql security definer set search_path = '' as $$
  update public.booking_notices set seen = true where id = p_id and member_id = public.current_member_id()
$$;

do $$ declare f text; begin
  foreach f in array array['admin_cancel_booking(bigint, text)', 'admin_move_booking(bigint, bigint, text)', 'seen_booking_notice(bigint)'] loop
    execute format('revoke execute on function public.%s from public, anon', f);
    execute format('grant execute on function public.%s to authenticated', f);
  end loop;
end $$;
